export interface ManagedMediaItem {
  id: string;
  category: "hero" | "leadership" | "technology" | "products" | "branding";
  categoryLabel: string;
  title: string;
  description: string;
  filename: string;
  appearsOn: string;
  pageRoute: string;
  aspectRatio: string;
}

export const MEDIA_CATALOG: ManagedMediaItem[] = [
  // 1. Hero Carousel & Main
  {
    id: "hero-1",
    category: "hero",
    categoryLabel: "Hero Carousel",
    title: "Hero Slide 1 — Luxury Atrium Glass Lift",
    description: "Primary entrance carousel banner showing high-rise luxury panoramic glass elevator.",
    filename: "carousel-hero-1.jpg",
    appearsOn: "Home Page (Hero #1)",
    pageRoute: "/",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "hero-2",
    category: "hero",
    categoryLabel: "Hero Carousel",
    title: "Hero Slide 2 — Bespoke Villa & Home Lift",
    description: "Second slide showcasing residential duplex and bungalow panoramic elevator.",
    filename: "carousel-hero-2.jpg",
    appearsOn: "Home Page (Hero #2)",
    pageRoute: "/",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "hero-3",
    category: "hero",
    categoryLabel: "Hero Carousel",
    title: "Hero Slide 3 — Commercial High-Traffic Core",
    description: "Third slide featuring corporate group-dispatch high-speed passenger elevators.",
    filename: "carousel-hero-3.jpg",
    appearsOn: "Home Page (Hero #3)",
    pageRoute: "/",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "hero-4",
    category: "hero",
    categoryLabel: "Hero Carousel",
    title: "Hero Slide 4 — Heavy Freight & Goods Lift",
    description: "Fourth slide highlighting industrial warehouse 5000+ kg capacity freight handler.",
    filename: "carousel-hero-4.jpg",
    appearsOn: "Home Page (Hero #4)",
    pageRoute: "/",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "hero-atrium",
    category: "hero",
    categoryLabel: "Hero Carousel",
    title: "Applications Header & Villa Glass Panoramic",
    description: "Cinematic header banner used on the Applications by Sector page.",
    filename: "glass-atrium-elevator.jpg",
    appearsOn: "Applications Page Header",
    pageRoute: "/applications",
    aspectRatio: "16:9 Landscape",
  },

  // 2. Leadership & Facilities
  {
    id: "leader-rajiv",
    category: "leadership",
    categoryLabel: "Leadership & Hub",
    title: "Rajiv Kumar Sethi — Founder & Engineering Head",
    description: "Executive portrait for technical leadership desk, consultation, and safety oversight.",
    filename: "rajiv-kumar-sethi.jpg",
    appearsOn: "About Us Page & Gallery",
    pageRoute: "/about",
    aspectRatio: "Portrait / 3:4",
  },
  {
    id: "facility-drone",
    category: "leadership",
    categoryLabel: "Leadership & Hub",
    title: "Cuttack Operations Hub — Aerial Drone View",
    description: "Ultra-HQ branded aerial drone view of the Rajabagicha, Cuttack central headquarters.",
    filename: "cuttack-facility-drone.jpg",
    appearsOn: "About Us Page (Header & Hub)",
    pageRoute: "/about",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "facility-team",
    category: "leadership",
    categoryLabel: "Leadership & Hub",
    title: "Engineering Team & Operational Fleet",
    description: "Company technical team and field operations service personnel.",
    filename: "company-team.jpg",
    appearsOn: "About Us Gallery",
    pageRoute: "/about",
    aspectRatio: "16:9 Landscape",
  },

  // 3. Core Technology & Safety
  {
    id: "tech-pmsm",
    category: "technology",
    categoryLabel: "Technology & Safety",
    title: "PMSM Gearless Traction Drive Machine",
    description: "Close-up technical appraisal of permanent-magnet synchronous gearless drive.",
    filename: "pmsm-gearless-motor.jpg",
    appearsOn: "About Us (Engineering Rigor) & Gallery",
    pageRoute: "/about",
    aspectRatio: "Landscape",
  },
  {
    id: "tech-door",
    category: "technology",
    categoryLabel: "Technology & Safety",
    title: "Landing Door Header & Multi-Point Interlock",
    description: "Telescopic car door header, infrared light curtain, and fail-safe mechanical lock.",
    filename: "door-mechanism-inspection.jpg",
    appearsOn: "About Us Gallery (Safety Systems)",
    pageRoute: "/about",
    aspectRatio: "Landscape",
  },
  {
    id: "tech-controller",
    category: "technology",
    categoryLabel: "Technology & Safety",
    title: "Microprocessor & V3F Controller Calibration",
    description: "Variable frequency drive panel diagnostics, automatic rescue devices (ARD).",
    filename: "controller-engineering.jpg",
    appearsOn: "Contact Page Header & Gallery",
    pageRoute: "/contact",
    aspectRatio: "16:9 Landscape",
  },
  {
    id: "tech-install",
    category: "technology",
    categoryLabel: "Technology & Safety",
    title: "Shaft Erection & Laser Rail Alignment",
    description: "On-site mechanical erection with sub-millimeter laser guide rail alignment.",
    filename: "installation-site.jpg",
    appearsOn: "Applications Bottom Banner & Gallery",
    pageRoute: "/applications",
    aspectRatio: "Landscape",
  },

  // 4. Product Lines
  {
    id: "prod-passenger",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Passenger Elevators (Residential & Commercial)",
    description: "Primary catalog image for passenger vertical transit systems.",
    filename: "passenger-elevator.jpg",
    appearsOn: "Products Catalog & Sector Details",
    pageRoute: "/products/passenger-elevators",
    aspectRatio: "Landscape",
  },
  {
    id: "prod-home",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Home & Villa Luxury Lifts",
    description: "Primary catalog image for bungalows, duplexes, and shallow pit home lifts.",
    filename: "home-elevator.jpg",
    appearsOn: "Products Catalog & Sector Details",
    pageRoute: "/products/home-villa-lifts",
    aspectRatio: "Landscape",
  },
  {
    id: "prod-hospital",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Hospital & Stretcher Lifts",
    description: "Primary catalog image for medical beds, healthcare clinics, and ICU lifts.",
    filename: "hospital-elevator.jpg",
    appearsOn: "Products Catalog & Sector Details",
    pageRoute: "/products/hospital-stretcher-lifts",
    aspectRatio: "Landscape",
  },
  {
    id: "prod-industrial",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Industrial Goods & Freight Lifts",
    description: "Primary catalog image for manufacturing plants and warehouse heavy freight lifts.",
    filename: "industrial-elevator.jpg",
    appearsOn: "Products Catalog & Sector Details",
    pageRoute: "/products/industrial-goods-lifts",
    aspectRatio: "Landscape",
  },
  {
    id: "prod-cabin",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Luxury Cabin Interiors & Finishes",
    description: "Hairline stainless steel and mirror gold architectural cabin finish details.",
    filename: "cabin-interior-luxury.jpg",
    appearsOn: "Products Catalog Detail",
    pageRoute: "/products",
    aspectRatio: "Landscape",
  },
  {
    id: "prod-hero",
    category: "products",
    categoryLabel: "Product Catalog",
    title: "Elevator Products Catalog Header",
    description: "Main header visual on the Products index page.",
    filename: "hero-elevator.jpg",
    appearsOn: "Products Page Header",
    pageRoute: "/products",
    aspectRatio: "16:9 Landscape",
  },

  // 5. Banners & Branding
  {
    id: "brand-logo",
    category: "branding",
    categoryLabel: "Branding & Banners",
    title: "Official Tejas Elevator Logo",
    description: "Official brand artwork featured on the top navigation bar and footer.",
    filename: "tejas-logo.jpg",
    appearsOn: "Navbar & Footer (Site-Wide)",
    pageRoute: "/",
    aspectRatio: "Square / 1:1",
  },
  {
    id: "banner-service",
    category: "branding",
    categoryLabel: "Branding & Banners",
    title: "Services & Lifecycle Support Banner",
    description: "Technician maintenance hero banner on the Services & AMC page.",
    filename: "technician-service.jpg",
    appearsOn: "Services & AMC Header",
    pageRoute: "/services",
    aspectRatio: "16:9 Landscape",
  },
];
